/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Metadata } from "./IERC20Metadata";
export type { TestToken } from "./TestToken";
export type { TestTokenReward } from "./TestTokenReward";
